### ISSUE TITLE
Code Review 2021/04/06

### ISSUE THREAD

**Issue by El-Potato-Slayer** [El-Potato-Slayer/Illusioned-game#1]
Finish the game. You're wasting time.

**Comment by El-Potato-Slayer** [comment]
@El-Potato-Slayer I'm sorry, pappie. I'll finish it as soon as possible :(

**Comment by El-Potato-Slayer** [comment]
@El-Potato-Slayer You better or I'll put chili in your willy

**Comment by El-Potato-Slayer** [comment]
@El-Potato-Slayer UwU that sounds amazing hehe

**Comment by El-Potato-Slayer** [comment]
@El-Potato-Slayer ye

**Comment by anewman15** [comment]
Thanks for all the feedback. There was a typo on line 12, column 33 in index.js. I fixed that
